[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"

[deploy]
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3

[service]
internal_port = "80"
auto_deploy = true
privileged = true

[variables]
base_dn = "$RAILWAY_DOMAIN"
RUDI_PORTAL_VERSION = "latest"
MAGNOLIA_VERSION = "latest"
DATAVERSE_VERSION = "latest"
POSTGRES_VERSION = "13"
DOCKER_BUILDKIT = "1"
COMPOSE_DOCKER_CLI_BUILD = "1"
