[build]
builder = "DOCKERFILE"
dockerfilePath = "./image/rudi-portal/Dockerfile"

[deploy]
startCommand = "docker compose -f docker-compose-magnolia.yml -f docker-compose-rudi.yml -f docker-compose-dataverse.yml -f docker-compose-network.yml --profile '*' up"
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3

[variables]
base_dn = "$RAILWAY_DOMAIN"
RUDI_PORTAL_VERSION = "latest"
MAGNOLIA_VERSION = "latest"
DATAVERSE_VERSION = "latest"
POSTGRES_VERSION = "13"
DOCKER_BUILDKIT = "1"
COMPOSE_DOCKER_CLI_BUILD = "1"
